# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1.xci
# IP: The module: 'design_for_gpio_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_for_gpio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_for_gpio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_for_gpio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1.xci
# IP: The module: 'design_for_gpio_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_for_gpio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_for_gpio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Xilinx/Seconda_tipologia/vivado_project/project_gpio/project_gpio.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_for_gpio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
