# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pad_lcoation.xdc

# Block Designs: bd/design_for_gpio/design_for_gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio || ORIG_REF_NAME==design_for_gpio}]

# IP: bd/design_for_gpio/ip/design_for_gpio_processing_system7_0_0/design_for_gpio_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_processing_system7_0_0 || ORIG_REF_NAME==design_for_gpio_processing_system7_0_0}]

# IP: bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_0/design_for_gpio_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_axi_gpio_0_0 || ORIG_REF_NAME==design_for_gpio_axi_gpio_0_0}]

# IP: bd/design_for_gpio/ip/design_for_gpio_axi_gpio_0_1/design_for_gpio_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_axi_gpio_0_1 || ORIG_REF_NAME==design_for_gpio_axi_gpio_0_1}]

# IP: bd/design_for_gpio/ip/design_for_gpio_ps7_0_axi_periph_0/design_for_gpio_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_for_gpio_ps7_0_axi_periph_0}]

# IP: bd/design_for_gpio/ip/design_for_gpio_rst_ps7_0_100M_0/design_for_gpio_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_for_gpio_rst_ps7_0_100M_0}]

# IP: bd/design_for_gpio/ip/design_for_gpio_xbar_0/design_for_gpio_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_xbar_0 || ORIG_REF_NAME==design_for_gpio_xbar_0}]

# IP: bd/design_for_gpio/ip/design_for_gpio_auto_pc_0/design_for_gpio_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_auto_pc_0 || ORIG_REF_NAME==design_for_gpio_auto_pc_0}]

# XDC: bd/design_for_gpio/design_for_gpio_ooc.xdc
