webtalk_init -webtalk_dir /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Custom/Terza_Tipologia/vivado_project/project_gpio_custom_int/gpio_project.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-07-12 15:57:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6fqq7jvof7jafh5h507bq5vb8m" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1499874878000" -context "sdk\\\\bsp/1499874878000"
webtalk_add_data -client sdk -key hwid -value "1499873324000" -context "sdk\\\\bsp/1499874878000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1499874878000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1499874878000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1499874878000"
webtalk_add_data -client sdk -key uid -value "1499874879000" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key hwid -value "1499873324000" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key bspid -value "1499874878000" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key projSize -value "173.94921875" -context "sdk\\\\application/1499874879000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1499875074088"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1499875074088"
webtalk_transmit -clientid 4153941314 -regid "" -xml /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Custom/Terza_Tipologia/vivado_project/project_gpio_custom_int/gpio_project.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Custom/Terza_Tipologia/vivado_project/project_gpio_custom_int/gpio_project.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/daniele/Sistemi_Embedded/Esercitazione_7/Driver/Esercitazione_7/Driver_GPIO_Custom/Terza_Tipologia/vivado_project/project_gpio_custom_int/gpio_project.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
