# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0.xci
# IP: The module: 'design_gpio_interrupt_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_interrupt_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_interrupt_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_interrupt_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0.xci
# IP: The module: 'design_gpio_interrupt_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_interrupt_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_interrupt_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/daniele/Scrivania/workspace_master/zybo_base_system/source/hw/project_gpio_interrupt/project_gpio_interrupt.srcs/sources_1/bd/design_gpio_interrupt/ip/design_gpio_interrupt_rst_ps7_0_100M_0/design_gpio_interrupt_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_interrupt_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
