# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ciro/Scrivania/SE/Elaborati/Elaborato1/gpio_project/gpio_project.tmp/my_gpio_v1_0_project/my_gpio_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/ciro/Scrivania/SE/Elaborati/Elaborato1/gpio_project/gpio_project.tmp/my_gpio_v1_0_project/my_gpio_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/ciro/Scrivania/SE/Elaborati/Elaborato1/ip_repo/my_gpio_1.0
  /home/ciro/Scrivania/SE/Elaborati/Elaborato1/ip_repo/my_gpio_1.0
} [current_project]
read_vhdl -library xil_defaultlib {
  /home/ciro/Scrivania/SE/gpio.vhd
  /home/ciro/Scrivania/SE/gpio_array.vhd
  /home/ciro/Scrivania/SE/Elaborati/Elaborato1/ip_repo/my_gpio_1.0/hdl/my_gpio_v1_0_S00_AXI.vhd
  /home/ciro/Scrivania/SE/Elaborati/Elaborato1/ip_repo/my_gpio_1.0/hdl/my_gpio_v1_0.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top my_gpio_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef my_gpio_v1_0.dcp

catch { report_utilization -file my_gpio_v1_0_utilization_synth.rpt -pb my_gpio_v1_0_utilization_synth.pb }
