# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/constrs_1/new/pad_location.xdc

# Block Designs: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/design_for_gpio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio || ORIG_REF_NAME==design_for_gpio}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_processing_system7_0_1/design_for_gpio_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_processing_system7_0_1 || ORIG_REF_NAME==design_for_gpio_processing_system7_0_1}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_my_gpio_0_0/design_for_gpio_my_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_my_gpio_0_0 || ORIG_REF_NAME==design_for_gpio_my_gpio_0_0}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_my_gpio_0_1/design_for_gpio_my_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_my_gpio_0_1 || ORIG_REF_NAME==design_for_gpio_my_gpio_0_1}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_my_gpio_0_3/design_for_gpio_my_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_my_gpio_0_3 || ORIG_REF_NAME==design_for_gpio_my_gpio_0_3}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_ps7_0_axi_periph_0/design_for_gpio_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_for_gpio_ps7_0_axi_periph_0}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_rst_ps7_0_100M_0/design_for_gpio_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_for_gpio_rst_ps7_0_100M_0}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_xbar_1/design_for_gpio_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_xbar_1 || ORIG_REF_NAME==design_for_gpio_xbar_1}]

# IP: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_auto_pc_2/design_for_gpio_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_for_gpio_auto_pc_2 || ORIG_REF_NAME==design_for_gpio_auto_pc_2}]

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_processing_system7_0_1/design_for_gpio_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_for_gpio_processing_system7_0_1 || ORIG_REF_NAME==design_for_gpio_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_rst_ps7_0_100M_0/design_for_gpio_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_for_gpio_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_for_gpio_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_rst_ps7_0_100M_0/design_for_gpio_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_for_gpio_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_for_gpio_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_rst_ps7_0_100M_0/design_for_gpio_rst_ps7_0_100M_0_ooc.xdc

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_xbar_1/design_for_gpio_xbar_1_ooc.xdc

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/ip/design_for_gpio_auto_pc_2/design_for_gpio_auto_pc_2_ooc.xdc

# XDC: /home/daniele/Scrivania/Elaborato1_NoInt_Driver_C/gpio_project/gpio_project.srcs/sources_1/bd/design_for_gpio/design_for_gpio_ooc.xdc
